config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :teachers
  resources :students
  resources :reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "students#index"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher
  has_many :reports

  has_many :enrollments
  has_many :courses, :through => :enrollments

  def at_risk
    if missing_assignments >= 3
      true
    else
      false
    end
  end

  def students_enrollments
    students = Student.all
    students.each do |student|
      student
      student.enrollments.each do |enrollment|
        enrollment
      end
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    puts('********************************************')
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :last_login, :teacher_id, :missing_assignments)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, class: "contents") do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_login %>
    <%= form.datetime_field :last_login, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= student.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last login:</strong>
    <%= student.last_login %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this student", student, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this student', edit_student_path(student), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/students/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing student</h1>

  <%= render "form", student: @student %>

  <%= link_to "Show this student", @student, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to students", students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/students/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <table>
    <colgroup>
      <col class="name">
      <col class="alias">
      <col class="super-abilities">
      <col class="age">
      <col class="status">
    </colgroup>
    <thead>
    <tr>
      <th class="name">Name</th>
      <th class="alias">At Risk</th>
      <th class="super-abilities">Last Login</th>
      <th class="age">Missing Assignments</th>
      <th class="status">Preview</th>
      <th class="status">Latest Report</th>
    </tr>
    </thead>
    <tbody>
    <% @students.each do |student| %>
      <tr>
        <td class="text-align-left"><%= student.name %></td>
        <td class="text-align-center">
          <% if student.at_risk%>
            <div class="icon-container text-red-500">
              <i class="fa-solid fa-exclamation-circle text-red-500"></i>
              At Risk
            </div>
          <% else %>
            <div class="icon-container">
              <i class="fa-solid fa-circle-check text-green-500"></i>
            </div>
          <% end %>
        </td>
        <td class="text-align-center"><%= student.last_login %></td>
        <td class="text-align-center"><%= student.missing_assignments %></td>
        <td class="text-align-center"><%= link_to 'Generate Report', new_report_path({ report: { student: student.attributes, student_id: student.id } }) %></td>
        <td class="text-align-center"><%= student.reports.order('date').last&.date&.strftime("%m/%d/%Y") %></td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td class="text-align-center" colspan="6">This table contains a list of students and their pertinent information, along with a way to generate a
        report. <br>**Students are at risk if missing more than two assignments
      </td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/students/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New student</h1>

  <%= render "form", student: @student %>

  <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/students/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @student %>

    <%= link_to 'Edit this student', edit_student_path(@student), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this student', student_path(@student), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>