config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :teachers
  resources :students
  resources :reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "students#index"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :student
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[ show edit update destroy ]

  # GET /reports or /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1 or /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
    @student = report_params[:student]
    @student_id = report_params[:student_id]
    puts(@student_id)
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports or /reports.json
  def create
    puts("report_params: #{report_params}")
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to report_url(@report), notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to report_url(@report), notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def report_params
      params.require(:report).permit(:date, :comments, :student_id, :name, :last_login, :teacher_id, :missing_assignments)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, class: "contents") do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :student_id, value: student_id %>

  <h6>Student Snapshot Report for
    <%= DateTime.now.strftime('%m/%d/%Y') %>
  </h6>

  <%= form.hidden_field :date, value: DateTime.now %>
  <% student = Student.find(student_id) %>
  <% teacher = student.teacher %>

  <br>

  <div>
    <div class="inline-block">
      <h6>Student: </h6>
    </div>
    <div class="inline-block">
      <%= student.name %>
    </div>
  </div>

  <br>

  <div>
    <div class="inline-block">
      <h6>Teacher: </h6>
    </div>
    <div class="inline-block">
      <%= teacher.name %>
    </div>
  </div>

  <br>

  <div>
    <div class="inline-block">
      <h6>Last Login: </h6>
    </div>
    <div class="inline-block">
      <%= student.last_login %>
    </div>
  </div>

  <br>

  <div>
    <div class="inline-block">
      <h6>Missing Assignments: </h6>
    </div>
    <div class="inline-block">
      <% if student.missing_assignments >= 3 %>
        <div class="inline-block text-red-500">
          <%= student.missing_assignments %>
        </div>
      <% else %>
        <div class="inline-block">
          <%= student.missing_assignments %>
        </div>
      <% end %>
    </div>
  </div>

  <br>
  <hr>
  <br>

  <h6>Current Course Grades</h6>

  <div class="h-56 grid grid-cols-3 gap-4 content-around">

    <% student.enrollments.each do |enrollment| %>
      <% course = Course.find(enrollment.course_id) %>
      <div>
        <br>
        <div class="inline-block">
          <h6><%= form.label course.name %>: </h6>
        </div>
        <% if enrollment.grade <= 69 %>
          <div class="inline-block text-red-500">
            <%= enrollment.grade %>
          </div>
          <% else %>
        <div class="inline-block">
          <%= enrollment.grade %>
        </div>
          <% end %>
      </div>
    <% end %>
  </div>

  <br>

  <div class="my-5">
    <%= form.label :comments %>
    <%= form.text_area :comments, rows: 4, class: "block shadow rounded-md border border-black-500 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div style="float: right;">
    <%= form.submit class: "sm-btn sm-btn-primary", value: "Generate Snapshot Report" %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
  <h6>Student Snapshot Report for
    <%= DateTime.now.strftime('%m/%d/%Y') %>
  </h6>

  <% student = Student.find(report.student_id) %>
  <% teacher = student.teacher %>

  <br>

  <div>
    <div class="inline-block">
      <h6>Student: </h6>
    </div>
    <div class="inline-block">
      <%= student.name %>
    </div>
  </div>

  <br>

  <div>
    <div class="inline-block">
      <h6>Teacher: </h6>
    </div>
    <div class="inline-block">
      <%= teacher.name %>
    </div>
  </div>

  <br>

  <div>
    <div class="inline-block">
      <h6>Last Login: </h6>
    </div>
    <div class="inline-block">
      <%= student.last_login %>
    </div>
  </div>

  <br>

  <div>
    <div class="inline-block">
      <h6>Missing Assignments: </h6>
    </div>
    <div class="inline-block">
      <% if student.missing_assignments >= 3 %>
        <div class="inline-block text-red-500">
          <%= student.missing_assignments %>
        </div>
      <% else %>
        <div class="inline-block">
          <%= student.missing_assignments %>
        </div>
      <% end %>
    </div>
  </div>

  <br>
  <hr>
  <br>

  <h6>Current Course Grades</h6>
  <div class="h-56 grid grid-cols-3 gap-4 content-around">

    <% student.enrollments.each do |enrollment| %>
      <% course = Course.find(enrollment.course_id) %>
      <div>
        <br>
        <div class="inline-block">
          <h6><%=course.name %>: </h6>
        </div>
        <% if enrollment.grade <= 69 %>
          <div class="inline-block text-red-500">
            <%= enrollment.grade %>
          </div>
        <% else %>
          <div class="inline-block">
            <%= enrollment.grade %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <hr>
  <p class="my-5">
    <strong class="block font-medium mb-1">Comments:</strong>
    <%= report.comments %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this report", report, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this report', edit_report_path(report), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/reports/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing report</h1>

  <%= render "form", report: @report %>

  <%= link_to "Show this report", @report, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to reports", reports_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reports/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reports</h1>
    <%= link_to 'New report', new_report_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="reports" class="min-w-full">
    <%= render @reports %>
  </div>
</div>

app/views/reports/new.html.erb
<div>
  <div class="back-button-section">
    <button type="button" class="sm-btn sm-btn-tertiary">
      <i class="fa-light fa-arrow-left"></i>
      <%= link_to 'Go Back', students_path, class: 'sm-btn-tertiary text-gray-500' %>
    </button>

  </div>

  <div class="mx-auto md:w-2/3 w-full">
    <%= render "form", report: @report, student_id: @student_id, student: @student %>

  </div>
</div>

app/views/reports/show.html.erb
<div>
  <div class="back-button-section">
    <button type="button" class="sm-btn sm-btn-tertiary">
      <i class="fa-light fa-arrow-left"></i>
      <%= link_to 'Go Back', students_path, class: 'sm-btn-tertiary text-gray-500' %>
    </button>
  </div>
  <div class="mx-auto md:w-2/3 w-full flex">
    <div class="mx-auto">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      <p>*To save as PDF: right click -> print-> "Print as PDF" in printer choice dropdown.</p>
      <br>
      <%= render @report %>
    </div>
  </div>
</div>